name: Run jest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
      working-directory: ./front
    - name: Run tests
      run: yarn test
      working-directory: ./front
    - name: Create status
      run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.ACCESS_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
          "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }' \
          --fail
