name: Run jest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
      working-directory: ./front
    - name: Run tests
      run: yarn test
      working-directory: ./front
